/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedUpdateRouteImport } from './routes/_authed.update'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedPlansRouteImport } from './routes/_authed.plans'
import { Route as AuthedPaymentsRouteImport } from './routes/_authed.payments'
import { Route as AuthedLogsRouteImport } from './routes/_authed.logs'
import { Route as AuthedBotRouteImport } from './routes/_authed.bot'
import { Route as AuthedAccountsRouteImport } from './routes/_authed.accounts'
import { Route as AuthedAccountsIdRouteImport } from './routes/_authed.accounts.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUpdateRoute = AuthedUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPlansRoute = AuthedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPaymentsRoute = AuthedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLogsRoute = AuthedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBotRoute = AuthedBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsIdRoute = AuthedAccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAccountsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthedAccountsRouteWithChildren
  '/bot': typeof AuthedBotRoute
  '/logs': typeof AuthedLogsRoute
  '/payments': typeof AuthedPaymentsRoute
  '/plans': typeof AuthedPlansRoute
  '/settings': typeof AuthedSettingsRoute
  '/update': typeof AuthedUpdateRoute
  '/accounts/$id': typeof AuthedAccountsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AuthedAccountsRouteWithChildren
  '/bot': typeof AuthedBotRoute
  '/logs': typeof AuthedLogsRoute
  '/payments': typeof AuthedPaymentsRoute
  '/plans': typeof AuthedPlansRoute
  '/settings': typeof AuthedSettingsRoute
  '/update': typeof AuthedUpdateRoute
  '/': typeof AuthedIndexRoute
  '/accounts/$id': typeof AuthedAccountsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/accounts': typeof AuthedAccountsRouteWithChildren
  '/_authed/bot': typeof AuthedBotRoute
  '/_authed/logs': typeof AuthedLogsRoute
  '/_authed/payments': typeof AuthedPaymentsRoute
  '/_authed/plans': typeof AuthedPlansRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/update': typeof AuthedUpdateRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/accounts/$id': typeof AuthedAccountsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/bot'
    | '/logs'
    | '/payments'
    | '/plans'
    | '/settings'
    | '/update'
    | '/accounts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/bot'
    | '/logs'
    | '/payments'
    | '/plans'
    | '/settings'
    | '/update'
    | '/'
    | '/accounts/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/accounts'
    | '/_authed/bot'
    | '/_authed/logs'
    | '/_authed/payments'
    | '/_authed/plans'
    | '/_authed/settings'
    | '/_authed/update'
    | '/_authed/'
    | '/_authed/accounts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/update': {
      id: '/_authed/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof AuthedUpdateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/plans': {
      id: '/_authed/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthedPlansRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/payments': {
      id: '/_authed/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthedPaymentsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/logs': {
      id: '/_authed/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthedLogsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bot': {
      id: '/_authed/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthedBotRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts/$id': {
      id: '/_authed/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AuthedAccountsIdRouteImport
      parentRoute: typeof AuthedAccountsRoute
    }
  }
}

interface AuthedAccountsRouteChildren {
  AuthedAccountsIdRoute: typeof AuthedAccountsIdRoute
}

const AuthedAccountsRouteChildren: AuthedAccountsRouteChildren = {
  AuthedAccountsIdRoute: AuthedAccountsIdRoute,
}

const AuthedAccountsRouteWithChildren = AuthedAccountsRoute._addFileChildren(
  AuthedAccountsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAccountsRoute: typeof AuthedAccountsRouteWithChildren
  AuthedBotRoute: typeof AuthedBotRoute
  AuthedLogsRoute: typeof AuthedLogsRoute
  AuthedPaymentsRoute: typeof AuthedPaymentsRoute
  AuthedPlansRoute: typeof AuthedPlansRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedUpdateRoute: typeof AuthedUpdateRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsRoute: AuthedAccountsRouteWithChildren,
  AuthedBotRoute: AuthedBotRoute,
  AuthedLogsRoute: AuthedLogsRoute,
  AuthedPaymentsRoute: AuthedPaymentsRoute,
  AuthedPlansRoute: AuthedPlansRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedUpdateRoute: AuthedUpdateRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
